#!/usr/bin/env bash
# Fails if the golden vectors under src/jvmTest/resources/vectors/ have drifted
# from void-which-binds-go's testvectors/vectors/ at the commit pinned in
# src/jvmTest/resources/vectors/VOID_WHICH_BINDS_GO_REF.
#
# void-which-binds-go is the single source of truth for Void-Which-Binds protocol vectors (its
# `testvectors` package); this repo carries a verbatim copy so the JVM tests can
# replay them. Never edit a copied vector here: re-copy it from void-which-binds-go and
# bump the pin in the same change.
#
# Env:
#   VOID_WHICH_BINDS_GO_TOKEN  token that can read the (private) void-which-binds-go repo over
#                      HTTPS; optional when your git already has credentials.
#   VOID_WHICH_BINDS_GO_URL    clone URL or local path (default: the GitHub repo).
#
# Paths that exist only here (not generated by void-which-binds-go) are excluded from
# the comparison: offload/ (heyarr-core's cruciform vectors), the README files
# and the pin file itself.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
vectors="$root/src/jvmTest/resources/vectors"
pin_file="$vectors/VOID_WHICH_BINDS_GO_REF"
url="${VOID_WHICH_BINDS_GO_URL:-${VOIDBIND_GO_URL:-https://github.com/rarebit-one/void-which-binds-go.git}}" # k0:keep: the gen1 env name is a fallback (ADR-0013 legacy)

ref="$(sed -e 's/#.*//' "$pin_file" | tr -d '[:space:]')"
if [[ ! "$ref" =~ ^[0-9a-f]{40}$ ]]; then
  echo "::error file=src/jvmTest/resources/vectors/VOID_WHICH_BINDS_GO_REF::expected a full 40-char void-which-binds-go commit SHA, got '$ref'" >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The gen1 names VOIDBIND_GO_TOKEN / VOIDBIND_GO_URL still work (ADR-0013 legacy).
VOID_WHICH_BINDS_GO_TOKEN="${VOID_WHICH_BINDS_GO_TOKEN:-${VOIDBIND_GO_TOKEN:-}}" # k0:keep
auth=()
if [[ -n "${VOID_WHICH_BINDS_GO_TOKEN:-}" ]]; then
  basic="$(printf 'x-access-token:%s' "$VOID_WHICH_BINDS_GO_TOKEN" | base64 | tr -d '\n')"
  auth=(-c "http.https://github.com/.extraheader=AUTHORIZATION: basic $basic")
fi

git -C "$work" init -q
git ${auth[@]+"${auth[@]}"} -C "$work" fetch -q --depth 1 "$url" "$ref"
git -C "$work" checkout -q FETCH_HEAD -- testvectors/vectors

upstream="$work/testvectors/vectors"
if diff -r -u \
  --exclude=README.md --exclude=offload --exclude=VOID_WHICH_BINDS_GO_REF \
  "$upstream" "$vectors"; then
  echo "vectors match void-which-binds-go@$ref"
else
  echo "::error::src/jvmTest/resources/vectors has drifted from void-which-binds-go testvectors/vectors@$ref. Re-copy the files from void-which-binds-go (never hand-edit them) and bump VOID_WHICH_BINDS_GO_REF in the same change." >&2
  exit 1
fi
